# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - grup03-sostenibilitat-dynamx

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
    build:
      runs-on: windows-latest
      permissions:
        contents: read

      steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Restore dependencies
        run: dotnet restore ProjecteSOS_Grup03.sln

      - name: Build solution
        run: dotnet build ProjecteSOS_Grup03.sln --configuration Release

      - name: Publish WebApp
        run: dotnet publish ./ProjecteSOS_Grup03WebPage/ProjecteSOS_Grup03WebPage.csproj -c Release -o "${{env.DOTNET_ROOT}}/publish/WebApp"

      - name: Publish API
        run: dotnet publish ./ProjecteSOS_Grup03API/ProjecteSOS_Grup03API.csproj -c Release -o "${{env.DOTNET_ROOT}}/publish/Api"

      - name: Combine publish folders
        run: |
          mkdir "${{env.DOTNET_ROOT}}/myapp"
          cp -r ${{env.DOTNET_ROOT}}/publish/WebApp/* ${{env.DOTNET_ROOT}}/myapp/
          cp -r ${{env.DOTNET_ROOT}}/publish/Api/* ${{env.DOTNET_ROOT}}/myapp/

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp
